### PR TITLE
Bound queries to the base element

### LINKED ISSUE #98: Provide options to adapt the document before mount
**Describe the feature**
We are using Vuetify as component library in one of our projects. I would like to introduce vue-testing-library and came up with some setup troubles on the way. Vuetify requires a wrapper element containing the attribute `data-app`. This element is used to append components like dialog to the root DOM level. The required setup can be done using jest setup files. Thought, the dialog content can not be found when using the exposed queries of the vue-testing-libraries `render()` method.

**To Reproduce**

- Init a vue app with vuetify
- Create a basic dialog
- write a test which should validate that the dialog content is visible when a button is clicked
- Add Vuetify and `<div data-app></div>` to your test DOM instance before mount

=> queries like getByText will not query the dialog content

I tried to create a codesandbox, but failed. Is there a working example for vue-testing-library?
https://codesandbox.io/s/vuetify-with-vue-testing-library-bhu8f?previewwindow=tests

**Expected behavior**
I expect a configuration option like it exists for react:

- baseElement: Specify the base element for the queries.
- container: Specify the surrounding DOM node

**Related information:**

- `@testing-library/vue` version: 3.0.0
- `Vue` version: 2.5.18
- `node` version: 8.12.0
- `yarn` version: 1.17.3
- `Vuetify` version: 1.2.10

Relevant code or config (if any)

```javascript
import CreateLorem from "./CreateLorem";
import { render } from "@testing-library/vue";
import Vuetify from "vuetify";
import Vue from "vue";

var app = document.createElement("div");
app.setAttribute("data-app", true);
document.body.appendChild(app);
Vue.use(Vuetify);

it("should create a lorem", () => {
  const { getByText } = render(CreateLorem);
  getByText("open");
});
```

### PR DESCRIPTION
**Pull request by afontcu**
This PR aims to fix several issues when trying to query content outside of the regular DOM node tree (portals, modals, etc). It tries to mirror React Testing Library behavior.

I also added a test based on Vuetify, because (1) it is related to the introduced changes and (2) Vuetify is widely-used and comes with its own nuances.

This is a **breaking change** since `container` and `baseElement` changed their meaning.

This PR closes #98

### CODE REVIEW

File: src/vue-testing-library.js [hunk 1]
```diff
@@ -53,15 +57,12 @@ function render(
   })
 
   mountedWrappers.add(wrapper)
-
-  const div = document.createElement('div')
-  wrapper.element.parentNode.insertBefore(div, wrapper.element)
```
Comment (afontcu) [inline src/vue-testing-library.js]: I'm not 100% sure this line should be gone. If I add it back, [this inline snapshot](https://github.com/testing-library/vue-testing-library/pull/100/files#diff-b45a2abc5c6c583db5549af5a49a2aa7R19) changes to `<blink></blink>`, and I don't think that's the desired output.

@dfcook could you double check that the logic here is no longer necessary as long as we append `wrapper.element` to our container (which is, in turn, a `<div>` wrapped in a `<body>`)?

**Comment by dfcook** [comment]
All looks good to me, I think the resulting code is a lot cleaner as well.

File: src/vue-testing-library.js (hunk 1 above)
Comment (dfcook) [reply src/vue-testing-library.js]: I agree, given that we are now in control of the container we can remove this logic.

File: src/__tests__/render.js [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+  expect(baseElement).toBe(document.body)
+})
+
+test('returns custom baseElement', () => {
+  const {baseElement} = render(
+    {
+      template: '<div />',
+    },
+    {
+      baseElement: document.createElement('blink'),
```
Comment (ChristophWalter) [inline src/__tests__/render.js]: I really like the new interface. But it is different from the react one which might be misleading. There a `container` is used to create an element and the `baseElement` just acts as pointer to that: https://testing-library.com/docs/react-testing-library/api#container

Comment (afontcu) [reply src/__tests__/render.js]: Hm, I see. I kind of like our API better, but it's true that keeping things as simillar as possible is a must. Thanks for pointing it out!

**Comment by afontcu** [comment]
@ChristophWalter @dfcook  I've updated the PR in order to make it similar to React Testing Library.

https://testing-library.com/docs/react-testing-library/api#container
