### PR TITLE
fix(rerender): Do not mount component again on rerender

### LINKED ISSUE #197: Unexpected parameter format for rerender() - v6 (next)
Hi,
The rerender function's signature on v6 is: 
```ts
rerender(props: object): Promise<void>
```
But this is how it works:
```ts
rerender({ props: { error: false } })
```
I think the `props` key is redundant and misleading here and it needs to be something like:
```ts
rerender({ error: false })
```

### PR DESCRIPTION
**Pull request by afontcu**
Closes #197 and #198

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -72,12 +66,7 @@ function render(
     unmount: () => wrapper.unmount(),
     html: () => wrapper.html(),
     emitted: () => wrapper.emitted(),
-    rerender: ({props}) => {
-      wrapper.unmount()
-      mountedWrappers.delete(wrapper)
-
-      wrapper = mountComponent(TestComponent, props)
-    },
+    rerender: props => wrapper.setProps(props),
```
Comment (afontcu) [inline src/index.js:69]: This is mostly it. Other changes are because we don't need a `wrapper` variable (and a `mountComponent` function) anymore.
