### PR TITLE
fix: support TypeScript v3

### LINKED ISSUE #240: Type errors with TypeScript 3.9.7
**Describe the bug** `tsc` compile fails with Typescript v3.9.7

**To Reproduce** Steps to reproduce the behavior:

See https://github.com/blimmer/vue-testing-library-issue / https://github.com/blimmer/vue-testing-library-issue/runs/2946243182?check_suite_focus=true

**Expected behavior**

The Typescript compile should pass with TypeScript v3.

**Screenshots**

Screen Shot 2021-06-29 at 2 31 48 PM

**Related information:**

- `@testing-library/vue` version: 5.8.0
- `Vue` version: N/A
- `node` version: 14
- `npm` (or `yarn`) version: N/A

Relevant code or config (if any)

```javascript
import '@testing-library/vue'
```

**Additional context**

Shouldn't the TypeScript check step of the CI system catch this?

### PR DESCRIPTION
**Pull request by blimmer**
I'm not sure if there's a more clever way to do this, but this should work. The linked issue has a reproduction example.

Fixes #240

### CODE REVIEW

File: types/index.d.ts [hunk 1]
```diff
@@ -46,16 +46,15 @@ export interface RenderOptions<V extends Vue, S = {}>
   baseElement?: Element
 }
 
-type ConfigurationArgs = [
```
Comment (afontcu) [inline types/index.d.ts:49]: out of curiosity, is this just a syntax change because TS 3.x does not support this type definition syntax?

Comment (blimmer) [reply types/index.d.ts:49]: Correct - I believe that format is called "named tuple" which is a new TS v4 feature.
